cursor            #ffb688
cursor_text_color #512400

foreground            #f0dfd7
background            #140d08
selection_foreground  #432b1c
selection_background  #e5bfa9
url_color             #e5bfa9

#: black 000000 767676
color0  #19120d
color8  #3d332d
#: red cc0403 f2201f
color1  #4a71a9
color9  #b0c2dc
#: green 19cb00 23fd00
color2  #e5bfa9
color10 #ffdbc7
#: yellow cecb00 fffd00
color3  #cac993
color11 #e7e6ad
#: blue 0d73cc 1a8fff
color4  #6e380f
color12 #ffb688
#: magenta cb1ed1 fd28ff
color5  #5b4130
color13 #e5bfa9
#: cyan 0dcdcd 14ffff
color6  #49491e
color14 #cac993
#: white dddddd ffffff
color7  #d7c3b8
color15 #f0dfd7

mark1_foreground #311300
mark1_background #ffdbc7
mark2_foreground #2b1709
mark2_background #ffdbc7
mark3_foreground #1d1d00
mark3_background #e7e6ad

active_tab_foreground #512400
active_tab_background #ffb688
inactive_tab_foreground #ffdbc7
inactive_tab_background #6e380f

active_border_color #ffb688
inactive_border_color #512400
# bell_border_color #ff5a00
